language: r
sudo: required
dist: trusty
cache:
  - packages
  - ccache
latex: false
r:
  - release
  #- oldrel
#  - devel

addons:
  postgresql: "9.6"
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
      - sourceline: 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'
        key_url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'
    packages:
      - libprotobuf-dev
      - protobuf-compiler
      - libv8-3.14-dev
      - libjq-dev
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev
      - libgdal-dev
      - libjson-c-dev
      - postgresql-server-dev-9.6

before_install:
  # install postgis from source:
  - wget http://download.osgeo.org/postgis/source/postgis-2.3.2.tar.gz
  - (mv postgis* /tmp; cd /tmp; tar xzf postgis-2.3.2.tar.gz)
  - (cd /tmp/postgis-2.3.2 ; ./configure; make; sudo make install)
  # create postgis databases:
  - sudo service postgresql restart
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - psql -d postgis -c "GRANT CREATE ON DATABASE postgis TO travis"
  - createdb empty
  - psql -d empty -c "CREATE EXTENSION postgis;"
  - R -q -e 'install.packages("devtools"); devtools::install_github("ropenscilabs/tic"); tic::prepare_all_stages()'

install: R -q -e 'tic::install()'
#script: R -q -e 'tic::script()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
   provider: script
   script: R -q -e 'tic::deploy()'
   on:
     branch: master
     condition: $TRAVIS_PULL_REQUEST = false

warnings_are_errors: true

after_success:
  - dropdb postgis
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - psql -d postgis -c "GRANT CREATE ON DATABASE postgis TO travis"
  - Rscript -e 'covr::codecov()'
